name       : ruby-erubi
version    : 1.9
release    : 1
source     :
    - https://rubygems.org/downloads/erubi-1.9.0.gem : 7d84d6037396418c4ba30bc40ed7a0aec9beb567ce55bcecb12e8c0cb1ed9fdb
license    : MIT
component  : programming.ruby
summary    : Erubi is a ERB template engine for ruby. It is a simplified fork of Erubis.
description: |
    Erubi is a ERB template engine for ruby. It is a simplified fork of Erubis.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
